# Generated by Django 5.0.3 on 2024-03-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desired_date', models.DateField()),
                ('notes', models.CharField(max_length=300)),
            ],
        ),
    ]
